#!/usr/bin/env python3
from __future__ import annotations
from pathlib import Path
import json,re,hashlib,statistics,math,csv
A=Path(__file__).resolve().parent; P=A.parent/'paper'; R=A/'results'
metrics=json.loads((R/'reviewer-metrics.json').read_text())
unc=json.loads((R/'paired-trace-uncertainty.json').read_text()) if (R/'paired-trace-uncertainty.json').exists() else {'comparisons':[]}
rows=metrics.get('merged_policy_rows',[])

def pick_main(policy):
    cand=[r for r in rows if r.get('policy')==policy and r.get('family')=='continuation_main']
    if not cand: cand=[r for r in rows if r.get('policy')==policy]
    # prefer rows with source mean and most query-like metric
    def score(r):
        q=max([float(v) for k,v in r.items() if isinstance(v,(int,float)) and 'quer' in k.lower()] or [0])
        has=1 if any('source' in k.lower() and 'byte' in k.lower() and 'mean' in k.lower() for k in r) else 0
        return (has,q,len(r))
    return max(cand,key=score) if cand else {}

def val(r,*parts):
    for k,v in r.items():
        kl=k.lower()
        if isinstance(v,(int,float)) and all(p in kl for p in parts): return float(v)
    return None
policies=['continuation_certificate','exact_delta_overlay','cut_aware_cache','full_coordinator_mirror','unsafe_stale']
main={p:pick_main(p) for p in policies}
for p,r in main.items():
    if p!='unsafe_stale' and not r: raise SystemExit(f'missing main row: {p}')

def src(r):
    x=val(r,'mean','source','byte')
    return x if x is not None else val(r,'source','byte')
def cli(r): return r.get('mean_client_payload_bytes')
def total(r): return r.get('mean_end_to_end_application_bytes')
def msgs(r): return val(r,'mean','source','message') or val(r,'source','message')
def state(r):
    return val(r,'max','logical','state','byte') or val(r,'logical','state','byte')

def pct(a,b): return (1-a/b)*100 if a is not None and b not in (None,0) else None
c=main['continuation_certificate'];o=main['exact_delta_overlay'];cc=main['cut_aware_cache'];m=main['full_coordinator_mirror']
summary={
 'source_reduction_vs_overlay_percent':pct(src(c),src(o)),
 'source_reduction_vs_cache_percent':pct(src(c),src(cc)),
 'source_reduction_vs_mirror_percent':pct(src(c),src(m)),
 'total_reduction_vs_overlay_percent':pct(total(c),total(o)),
 'total_reduction_vs_cache_percent':pct(total(c),total(cc)),
 'total_reduction_vs_mirror_percent':pct(total(c),total(m)),
 'mirror_state_multiple':state(m)/state(c) if state(m) and state(c) else None,
}
# Require end-to-end coverage before allowing the paper to make an end-to-end statement.
if any(total(x) is None for x in (c,o,cc,m)):
    raise SystemExit('end-to-end application metric unavailable for one or more safe main policies')

G=P/'generated';G.mkdir(exist_ok=True)
def texnum(x,d=3):
    if x is None:return '--'
    if abs(x)>=10000:return f'{x:,.0f}'
    return f'{x:,.{d}f}'
macros=[r'% generated by artifact/generate_reviewer_hardening.py']
for name,r in [('Continuation',c),('Overlay',o),('CutCache',cc),('Mirror',m)]:
    for suffix,v in [('SourceBytes',src(r)),('ClientBytes',cli(r)),('TotalBytes',total(r)),('Messages',msgs(r)),('StateBytes',state(r))]:
        macros.append(rf'\newcommand{{\Reviewer{name}{suffix}}}{{{texnum(v)}}}')
for k,v in summary.items():
    cmd=''.join(w.capitalize() for w in k.split('_'))
    macros.append(rf'\newcommand{{\Reviewer{cmd}}}{{{texnum(v,2)}}}')
(G/'reviewer_metrics_macros.tex').write_text('\n'.join(macros)+'\n')

table=r'''% generated; application-layer accounting only
\begin{table*}[t]
\centering
\small
\caption{Two traffic views for the frozen primary workload. Source-facing bytes count source RPC requests and replies. Client payload counts the canonical UTF-8 JSON result returned by the coordinator. Total is their sum; logical state is reported separately and is not converted into traffic.}
\label{tab:reviewer-accounting}
\begin{tabular}{lrrrrr}
\toprule
Policy & Source B/query & Client B/query & Total B/query & Source msg/query & Max logical state (B)\\
\midrule
Continuation certificate & \ReviewerContinuationSourceBytes & \ReviewerContinuationClientBytes & \ReviewerContinuationTotalBytes & \ReviewerContinuationMessages & \ReviewerContinuationStateBytes\\
Exact delta overlay & \ReviewerOverlaySourceBytes & \ReviewerOverlayClientBytes & \ReviewerOverlayTotalBytes & \ReviewerOverlayMessages & \ReviewerOverlayStateBytes\\
Cut-aware cache & \ReviewerCutCacheSourceBytes & \ReviewerCutCacheClientBytes & \ReviewerCutCacheTotalBytes & \ReviewerCutCacheMessages & \ReviewerCutCacheStateBytes\\
Full coordinator mirror & \ReviewerMirrorSourceBytes & \ReviewerMirrorClientBytes & \ReviewerMirrorTotalBytes & \ReviewerMirrorMessages & \ReviewerMirrorStateBytes\\
\bottomrule
\end{tabular}
\end{table*}
'''
(G/'reviewer_metrics_table.tex').write_text(table)

# Descriptive paired table, only comparisons with useful coverage.
comps=[x for x in unc.get('comparisons',[]) if x.get('paired_traces',0)>=2]
lines=[r'\begin{table}[t]',r'\centering',r'\small',r'\caption{Trace-paired source-byte differences (continuation minus baseline). Bootstrap intervals describe only the frozen trace set; they are not population-level significance claims.}',r'\label{tab:paired-uncertainty}',r'\begin{tabular}{lrrr}',r'\toprule',r'Baseline & $n$ & Mean diff. (B) & 95\% descriptive interval\\',r'\midrule']
label={'exact_delta_overlay':'Overlay','cut_aware_cache':'Cut cache','full_coordinator_mirror':'Mirror'}
for x in comps[:8]:
    lo,hi=x['bootstrap_95_interval_for_mean_difference'];lines.append(f"{label.get(x['baseline'],x['baseline'])} & {x['paired_traces']} & {x['mean_difference_bytes']:.1f} & [{lo:.1f}, {hi:.1f}]\\\\")
lines += [r'\bottomrule',r'\end{tabular}',r'\end{table}']
(G/'reviewer_uncertainty_table.tex').write_text('\n'.join(lines)+'\n')

appendix=r'''\section{Reviewer-facing accounting and validity audit}
\label{app:reviewer-hardening}
\input{generated/reviewer_metrics_table}
\input{generated/reviewer_uncertainty_table}

\paragraph{What changes under the broader accounting.}
The continuation design remains below exact overlay and the cut-aware cache in both source-facing and end-to-end application bytes on the frozen primary workload.  The full mirror is different: it uses fewer end-to-end application bytes per query, while retaining roughly \ReviewerMirrorStateMultiple$\times$ as much maximum logical coordinator state.  We therefore report a Pareto trade-off rather than claiming that continuation universally dominates mirroring.  Logical state, process RSS, application bytes, and transport overhead are distinct quantities; none is silently converted into another.

\paragraph{Measurement contract.}
Source-facing bytes are the exact compact-JSON request and response lengths recorded at source RPC boundaries.  Client bytes are recomputed from frozen raw records as compact UTF-8 JSON containing only client-visible result, status, certificate, and failure fields.  Oracle labels, timing, debug fields, and instrumentation counters are excluded.  End-to-end application bytes are the sum.  TCP/IP, TLS, allocator metadata, and process startup are outside this metric and are not estimated.

\paragraph{Finite-trace uncertainty.}
The paired bootstrap resamples complete trace-level differences with a fixed seed.  The intervals are descriptive sensitivity summaries for the finite scenario/seed set, not confidence intervals for an assumed iid production population and not $p$-values.

\paragraph{History cutoff.}
The public-history experiment remains a deliberately frozen function-level projection through cachetools v7.1.8 (commit \texttt{4500e3d}, 31 August 2026).  The repository subsequently released v7.2.0 (commit \texttt{3c082c6}, 16 September 2026).  That post-freeze release is recorded in the artifact's cutoff audit rather than silently folded into the prespecified result.  The experiment must therefore not be described as a current full-repository replay.

\paragraph{Unresolved external-validity boundaries.}
The evidence does not establish WAN performance, durable multi-host recovery, production code-search relevance, hostile-source security, or generality beyond the frozen ranker and workloads.  These are explicit non-claims, not inferred successes.  The artifact's reviewer matrix identifies the experiment or assumption needed to cross each boundary.
'''
(G/'reviewer_hardening_appendix.tex').write_text(appendix)

# Exact public-history cutoff audit using pinned upstream identifiers.
downloads=Path('$WORK_ROOT/downloads')
def fh(p):return hashlib.sha256(p.read_bytes()).hexdigest() if p.exists() else None
hist={
 'repository':'tkem/cachetools',
 'prespecified_baseline':{'tag':'v7.1.4','commit':'48284d73d0a8834c9c50f8d41bb99e6f93b2dfed','url':'https://github.com/tkem/cachetools/commit/48284d73d0a8834c9c50f8d41bb99e6f93b2dfed'},
 'prespecified_head':{'tag':'v7.1.8','commit':'4500e3d04288738d25acbb4973eb3c3e1bf41db9','date':'2026-08-31','url':'https://github.com/tkem/cachetools/commit/4500e3d04288738d25acbb4973eb3c3e1bf41db9'},
 'post_freeze_audit':{'tag':'v7.2.0','commit':'3c082c654c2804b9354e4b62dbd2994f1aac464d','date':'2026-09-16','url':'https://github.com/tkem/cachetools/commit/3c082c654c2804b9354e4b62dbd2994f1aac464d','included_in_prespecified_result':False},
 'downloaded_cross_check':{
  'baseline_cached_py_sha256':fh(downloads/'48284d-_cached.py'),
  'v7_2_0_cached_py_sha256':fh(downloads/'3c082c-_cached.py')},
 'scope':'function-level projection over the explicitly retained module/history inputs; not a full repository checkout replay',
 'reason_not_retrofitted':'preserve the frozen prespecified result and expose the later release as a cutoff audit rather than post-hoc expanding the favorable workload'
}
(R/'history-cutoff-audit.json').write_text(json.dumps(hist,indent=2,sort_keys=True))

# Reviewer matrix, separating closed issues from irreducible boundaries.
md=f'''# Reviewer-hardening audit

This audit is generated from frozen result records.  It distinguishes corrected reporting defects from evidence that is still outside the experiment.

## Closed in this revision

| Likely objection | Resolution | Evidence |
|---|---|---|
| Communication advantage depends on a selected boundary | Source-facing, client-return, and combined application bytes are all reported; state is separate. | `results/reviewer-metrics.json`, Table `reviewer-accounting` |
| Mirror comparison hides the metric on which mirror wins | The paper now states that mirror has lower end-to-end bytes on the frozen primary workload and reports the {summary['mirror_state_multiple']:.2f}x state trade-off. | generated macros/table and appendix |
| Deterministic traces are presented with population-style certainty | Trace-paired ranges and a deterministic bootstrap sensitivity interval are labeled descriptive, not inferential. | `results/paired-trace-uncertainty.json` |
| Public-history result can become silently stale | Baseline/head SHAs, cutoff date, and the post-freeze v7.2.0 audit are pinned. | `results/history-cutoff-audit.json` |
| Logical state is conflated with bytes on the wire | The definitions prohibit adding state bytes to traffic and define exclusions. | `results/reviewer-metrics.json` |
| A favorable aggregate can hide an unsafe policy | Exactness, false-completeness, and target-state validity remain separate gates. | frozen summaries and independent replay |

## Boundaries that cannot be honestly eliminated by this artifact

| Boundary | Current evidence | What would be required |
|---|---|---|
| Production query distribution | Deterministic repeated-query plans | Independently sourced, privacy-reviewed production query traces |
| Full repository evolution | Frozen function-level projection | Multi-repository full-tree checkout replay with renames/build metadata |
| Multi-host durability | Separate OS processes on one host | Durable logs and crash/recovery across independent hosts and disks |
| WAN performance | Loopback application-byte accounting | Controlled WAN emulation and real multi-region deployment |
| Ranking generality | Frozen local scorer | Re-run with production lexical/neural rankers whose score dependencies satisfy the certificate assumptions |
| Malicious sources | Crash/omission model | Authenticated, Byzantine-resilient completeness proofs |
| Universal optimality | Finite workloads and baselines | Lower bounds or a workload-independent optimality proof |

## Frozen primary accounting

| Policy | Source B/query | Client B/query | Total B/query | Max logical state B |
|---|---:|---:|---:|---:|
| Continuation | {src(c):.3f} | {cli(c):.3f} | {total(c):.3f} | {state(c):.0f} |
| Exact overlay | {src(o):.3f} | {cli(o):.3f} | {total(o):.3f} | {state(o) or 0:.0f} |
| Cut-aware cache | {src(cc):.3f} | {cli(cc):.3f} | {total(cc):.3f} | {state(cc):.0f} |
| Full mirror | {src(m):.3f} | {cli(m):.3f} | {total(m):.3f} | {state(m):.0f} |

The valid conclusion is a Pareto result: continuation reduces source-facing traffic and coordinator state relative to different baselines; it does not dominate the mirror on every traffic boundary.
'''
(A/'REVIEWER-HARDENING.md').write_text(md)
(R/'reviewer-hardening-summary.json').write_text(json.dumps({'main':main,'derived':summary,'metric_definition':metrics['definition']},indent=2,sort_keys=True))

# Patch paper safely and idempotently.
texfiles=[p for p in P.rglob('*.tex') if 'generated' not in p.parts]
maintex=P/'main.tex'
if not maintex.exists():
    maintex=max(texfiles,key=lambda p:len(p.read_text()))
mt=maintex.read_text()
if 'generated/reviewer_metrics_macros' not in mt:
    # macros must be loaded after packages and before first use; insert before begin document when possible.
    mt=mt.replace('\\begin{document}','\\input{generated/reviewer_metrics_macros}\n\\begin{document}',1)
if 'generated/reviewer_hardening_appendix' not in mt:
    mt=mt.replace('\\end{document}','\\input{generated/reviewer_hardening_appendix}\n\\end{document}',1)
maintex.write_text(mt)

# Abstract replacement: direct, bounded claims, no universal win.
abstract='''\\begin{abstract}
Federated code search must answer against repository cuts even when replicas lag, histories are compacted, or ownership changes.  We study continuation certificates: a client retains a bounded candidate buffer and a lower bound on every omitted result, advances that state over a verified update suffix, and fetches a new shard prefix only when the bound can still enter the global top-$k$.  A separate checker accepts completeness only when every shard is covered at the requested cut.  Conditional proofs establish target-state soundness and a $k+d$ repair bound under the stated ordered-log and rank-locality assumptions.

The prototype and finite checker find no false completeness claim for the safe policies in the frozen experiments.  On the primary repeated-query workload, continuation reduces source-facing application bytes relative to exact delta overlay and a cut-aware cache.  Broader accounting changes the comparison with a full coordinator mirror: the mirror returns fewer end-to-end application bytes per query, whereas continuation retains about \\ReviewerMirrorStateMultiple$\\times$ less maximum logical coordinator state.  Cold queries remain a negative result: one-shot prefix repair is more expensive than exact overlay.  The contribution is therefore a verified Pareto point for repeated queries under explicit assumptions, not a universal communication or deployment advantage.
\\end{abstract}'''
for p in texfiles:
    s=p.read_text()
    ns,n=re.subn(r'\\begin\{abstract\}.*?\\end\{abstract\}',abstract,s,count=1,flags=re.S)
    if n:
        p.write_text(ns);break

# Add accounting contract at start of Evaluation if absent.
insert='''
\\paragraph{Accounting contract.}
We report two application-layer traffic boundaries.  \\emph{Source-facing bytes} count compact-JSON requests and replies at source RPC boundaries.  \\emph{End-to-end application bytes} add the canonical client-visible coordinator response; they exclude oracle/debug fields and transport headers.  Logical state and process RSS are reported separately.  This distinction matters: continuation is below overlay and cut cache on both traffic views, but the full mirror has lower end-to-end bytes while retaining substantially more coordinator state (Appendix~\\ref{app:reviewer-hardening}).
'''
for p in texfiles:
    s=p.read_text()
    if re.search(r'\\section\{(?:Evaluation|Experimental Evaluation|Experiments)\}',s,re.I) and 'Accounting contract.' not in s:
        s=re.sub(r'(\\section\{(?:Evaluation|Experimental Evaluation|Experiments)\})',r'\1'+insert,s,count=1,flags=re.I)
        p.write_text(s);break

# Neutralize any universal mirror-traffic dominance sentence while preserving tables.
for p in texfiles:
    s=p.read_text()
    paras=re.split(r'(\n\s*\n)',s)
    changed=False
    for i,x in enumerate(paras):
        low=x.lower()
        if ('51.47' in x or '51.472' in x) and 'mirror' in low and ('communication' in low or 'bytes' in low):
            paras[i]='Continuation uses fewer source-facing bytes than the full mirror in this workload, but the mirror uses fewer end-to-end application bytes; the trade-off is the mirror\'s much larger logical coordinator state (Appendix~\\ref{app:reviewer-hardening}).'
            changed=True
    if changed:p.write_text(''.join(paras))

# Fresh conclusion if a conventional section is found.
conclusion='''\\section{Conclusion}
Continuation certificates make a narrow systems trade-off explicit: verified state carried across repeated queries can avoid most source re-fetches without retaining a full coordinator mirror.  The safety result is conditional on ordered, authenticated source evidence, rank-local scoring, and the stated ownership contract.  Evaluation supports a Pareto claim rather than universal dominance: continuation lowers source-facing traffic and state relative to different alternatives; a full mirror can use fewer end-to-end bytes, and exact overlay remains preferable for cold queries.  The artifact preserves these non-advantages, independent replay, metric definitions, and the public-history cutoff so that later work can test the remaining production, multi-host, and ranker-generalization boundaries.'''
for p in texfiles:
    s=p.read_text()
    pat=r'\\section\{Conclusion(?:s)?\}.*?(?=(?:\\section\{|\\bibliography|\\begin\{thebibliography\}|\\end\{document\}))'
    ns,n=re.subn(pat,conclusion+'\n\n',s,count=1,flags=re.S|re.I)
    if n:p.write_text(ns);break
print(json.dumps({'generated':True,'maintex':str(maintex),'summary':summary},sort_keys=True))
